version: '3'

services:
  web:
    container_name: backend
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/web
    ports:
      - "8000:8000"
    depends_on:
      - db
  app:
    container_name: frontend
    build: ./app
    command: yarn run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/code/web
    environment:
      - NODE_ENV=development
  db:
    image: postgres
    ports:
      - '5432'
  redis:
    image: "redis:alpine"

