

const REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
const REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
const REGISTER_FAILURE = 'USER_REGISTER_FAILURE';


const LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const LOGIN_FAILURE = 'USER_LOGIN_FAILURE';


const USER_LOGOUT = 'USER_LOGOUT';

export default {
    REGISTER_REQUEST
    REGISTER_SUCCESS
    REGISTER_FAILURE
    LOGIN_REQUEST
    LOGIN_SUCCESS
    LOGIN_FAILURE
    USER_LOGOUT    
}